### ISSUE TITLE
Centro de Treinamento

### ISSUE THREAD

**Issue by woliveiras** [jonathanslima/grupo-estudo-js#1]
Cara, você conhece a iniciativa [Centro de Treinamento](https://github.com/training-center/sobre)?

Chega junto com a gente pra agilizar os grupos de estudos de JavaScript! :smile:

**Comment by jonathanslima** [comment]
Opa @woliveiras, eu conheci através de um tweet teu e esse repo foi criado justamente pra documentar o meu progresso em um dos grupos que eu to. E talvez possa servir de template pro pessoal usar também.

**Comment by woliveiras** [comment]
Aee, show de bola cara!
